import AG2 from "./anhgame2.png"
export const lst=[{
    id:1,
    caption:"Search Engine",
    summary:"Đây là đồ án viết bộ công cụ tìm kiếm các file(đoạn văn bản) dựa trên từ khóa cho trước. Đồ án được thực hiện thông quan ngôn ngữ C++"
,
    link:"https://github.com/khoaking2002/Search-Engine",
    src:"https://cdn.searchenginejournal.com/wp-content/uploads/2021/08/great-search-engines-612f8f78d1f79-sej-1280x720.jpg",
    },
    {
        id:2,
        caption:"Detect fake news in Vietnamese",
        summary:"Đây là dự án nhằm tạo ra công cụ giúp phát hiện tin giả bằng tiếng việt. Đồ án sử dụng python và mô hình phoBERT",
        link:"https://drive.google.com/file/d/1ozSZT6eDergD1KuNyn37XTr6VrEaidKd/view?usp=sharing",
        src:"https://tuyengiao.vn/Uploads/2020/7/30/22/288.jpg",
    },
    {
        id:3,
        caption: "Tower Defense",
        summary: "Đây là đồ án game chiến thuật kinh điển. Người chơi sẽ bố trí địa hình nhằm tiêu diệt toàn bộ kẻ xâm lược",
        link:"https://github.com/khoaking2002/Tower-Defense",
        src:"https://github.com/khoaking2002/Tower-Defense/blob/main/anhgame2.png?raw=true",
    },
    {
        id:4,
        caption: "Simple game",
        summary:"Đây là đồ án game đơn giản, người chơi sẽ thực hiện việc né các vật rác rơi từ trên trời xuống, nhặt các vật phẩm đặc biệt để tăng sức mạnh",
        link:"https://github.com/khoaking2002/SimpleGame",
        src:"https://static.wixstatic.com/media/86cdcb_3bd53b954a0b442b891e0893cad0d24f~mv2.png/v1/fill/w_1962,h_1080,al_c,q_95,usm_0.66_1.00_0.01,enc_auto/137643221_522281988708133_35844665488083.png",
    },
    {
        id:5,
        caption: "BigInt",
        summary:"Đây là đồ án nhằm giúp người sử dụng thao tác được với các số nguyên cực lớn(cộng, trừ, nhân, chia, lũy thừa, kiểm tra số nguyên tố,...) trên cả hệ thập phân và nhị phân",
        link:"https://github.com/khoaking2002/BigInt",
        src:"https://a.fsdn.com/con/app/proj/cpp-bigint/screenshots/BigInt-5.0-screen2.jpg/max/max/1",
    },
    {
        id:6,
        caption:"Đồ án kiểm định và dự đoán",
        summary:"Đồ án sẽ thực hiện kiểm định các suy luận về lượng mưa(vùng A nhiều mưa hơn B) và dự đoán điểm sương dựa trên các yếu tố khác",
        link:"https://github.com/khoaking2002/LinearKiemDinh",
        src:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvG9bdc8QjvnqPo3y9LxewFX8TKOjj7KwXkDI_ZzEZkTH_loGRqJnaI_AZN9NvyOjG98c&usqp=CAU",
    },
    {
        id:7,
        caption:"Làm việc với hidden Markov",
        summary:"Đồ án gồm ba phần: lý thuyết về markov ẩn, thử nghiệm các thuật toán liên quan và ứng dụng để dự đoán giá trị cổ phiếu",
        link:"https://github.com/khoaking2002/Hidden-Markov",
        src:"https://i.ytimg.com/vi/RWkHJnFj5rY/maxresdefault.jpg",
    },
    {
        id:8,
        caption:"Tạo thiết bị truy vấn danh bạ từ xa",
        summary:"Đồ án sử dụng socket giúp chúng ta có thể tìm kiếm thông tin của người dùng thông qua sđt, tên, địa chỉ hoặc email",
        link:"https://github.com/khoaking2002/QueryPhone",
        src:"https://cachvaytiennganhang.com/wp-content/uploads/2021/11/app-vay-tien-truy-cap-danh-ba.jpg",
    },
    {
        id:9,
        caption:"Tạo thiết bị điều khiển laptop thông qua mail",
        summary:"Đồ án tạo ra hệ thống điều khiển một thiết bị khác qua mail. Ví dụ bạn muốn tắt máy chỉ cần nhắn \"Turn off computer\" đến máy đang đăng nhập mail đó",
        link:"https://github.com/khoaking2002/MailControl",
        src:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk3EVDMrVX3uubFT85nisbW30pfeFpUC-5wmhg1wkM-T2PA1RiS6fSEWlckdzgmZmt2R8&usqp=CAU",
    },
];
